package com.bage.mapper.db2;


import com.bage.domain.OauthClientDetails2;

public interface OauthClientDetailsMapper2 {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbg.generated Wed May 01 13:20:23 CST 2019
     */
    int deleteByPrimaryKey(String clientId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbg.generated Wed May 01 13:20:23 CST 2019
     */
    int insert(OauthClientDetails2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbg.generated Wed May 01 13:20:23 CST 2019
     */
    int insertSelective(OauthClientDetails2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbg.generated Wed May 01 13:20:23 CST 2019
     */
    OauthClientDetails2 selectByPrimaryKey(String clientId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbg.generated Wed May 01 13:20:23 CST 2019
     */
    int updateByPrimaryKeySelective(OauthClientDetails2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbg.generated Wed May 01 13:20:23 CST 2019
     */
    int updateByPrimaryKey(OauthClientDetails2 record);
}