use mydbpro;

DROP TABLE IF EXISTS tb_user;

CREATE TABLE tb_user
(
	id BIGINT(20) NOT NULL COMMENT '主键ID' AUTO_INCREMENT,
	first_name VARCHAR(32) NULL DEFAULT NULL COMMENT '姓',
	last_name VARCHAR(32) NULL DEFAULT NULL COMMENT '名',
    sex VARCHAR(16) NULL DEFAULT NULL COMMENT '性别，Male 男； Female 女',
	birthday Date NULL DEFAULT NULL COMMENT '年龄',
	address VARCHAR(128) NULL DEFAULT NULL COMMENT '地址',
	email VARCHAR(64) NULL DEFAULT NULL COMMENT '邮箱',
	phone VARCHAR(64) NULL DEFAULT NULL COMMENT '手机号',
	remark VARCHAR(28) NULL DEFAULT NULL COMMENT '备注、描述',
	PRIMARY KEY (id)
);




