spring:
  application:
    name: api-docs

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  show-actuator: false
  packages-to-scan: com.example.controller

server:
  port: 8080
