package com.bage.mapper.db1;

import com.bage.domain.OauthClientDetails1;

public interface OauthClientDetailsMapper1 {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbg.generated Wed May 01 13:20:23 CST 2019
     */
    int deleteByPrimaryKey(String clientId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbg.generated Wed May 01 13:20:23 CST 2019
     */
    int insert(OauthClientDetails1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbg.generated Wed May 01 13:20:23 CST 2019
     */
    int insertSelective(OauthClientDetails1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbg.generated Wed May 01 13:20:23 CST 2019
     */
    OauthClientDetails1 selectByPrimaryKey(String clientId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbg.generated Wed May 01 13:20:23 CST 2019
     */
    int updateByPrimaryKeySelective(OauthClientDetails1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbg.generated Wed May 01 13:20:23 CST 2019
     */
    int updateByPrimaryKey(OauthClientDetails1 record);
}