const Map<String, String> en = {
  'login': 'Login',
  'username': 'Username',
  'password': 'Password',
  'home': 'Home',
  'current_location': 'Current Location',
  'find_location': 'Find Location',
  'history_location': 'Location History',
  'track_location': 'Track Location',
  'tv_player': 'TV Player',
  'settings': 'Settings',
  'language_settings': 'Language Settings',
  'theme_color': 'Theme Mode',
  'current_language': 'Current Language',
  'current_theme': 'Current Theme',
  'family': 'My Family',
  'profile': 'Profile',
  'message': 'Message',
  'logout': 'Logout',
  'message_center': 'Message Center',
  'sender': 'Sender',
  'loading_more': 'Loading more...',
  'load_more': 'Load more', // 添加这个翻译键
  'fetch_message_failed': 'Failed to fetch messages',
  'user_login': 'User Login',
  'account': 'Account',
  'captcha': 'Captcha',
  'enter_account': 'Please enter account',
  'enter_password': 'Please enter password',
  'enter_captcha': 'Please enter captcha',
  'account_locked': 'Account locked, please try again in 10 minutes',
  'register_prompt': 'Don\'t have an account? Register now',
  'login_failed': 'Login failed',
  'unknown_error': 'Unknown error',
  'family_title': 'Family Tree',
  'loading_family_data': 'Loading family data...',
  'no_data': 'No data available',
  'unknown_member': 'Unknown Member',
  'unknown_relationship': 'Unknown Relationship',
  'switch_to_user': 'Switch to current user',
  'view_member_info': 'View member information',
  'error': 'Error',
  'confirm': 'Confirm',
  'cancel': 'Cancel',
  // 添加TV列表页面的翻译键
  'tv_list': 'TV List',
  'loading_tv_channels': 'Loading TV channels...',
  'search_channels': 'Search channels',
  'no_tv_channels_found': 'No TV channels found',
  'unknown_channel': 'Unknown channel',
  'signal_sources': 'signal sources',
  'page': 'Page',
  'current_page': 'Current Page',
  'total': 'Total',
  'channels': 'channels',
  'previous_page': 'Previous Page',
  'next_page': 'Next Page',

  // 添加发送消息功能的翻译键
  'send_message': 'Send Message',
  'message_sent_successfully': 'Message sent successfully',
  'message_sent_failed': 'Message sent failed',
  'receiver_id': 'Receiver ID',
  'enter_receiver_id': 'Please enter receiver ID',
  'message_content': 'Message Content',
  'enter_message_content': 'Please enter message content',
  'user_not_logged_in': 'User not logged in',
  'please_enter_all_fields': 'Please fill in all fields',
  
  // 添加家族编辑页面的翻译键
  'add_family_relationships': 'Add Relationships',
  'selected_user': 'Selected User',
  'select_user': 'Select User',
  'select_relationship': 'Select Relationship',
  'relationship_required': 'Relationship is required',
  'save_relationships': 'Save Relationships',
  'please_add_at_least_one_relationship': 'Please add at least one relationship',
  'success': 'Success',
  'relationships_saved': 'Relationships saved successfully',
  
  // 关系类型翻译
  'father': 'Father',
  'mother': 'Mother',
  'son': 'Son',
  'daughter': 'Daughter',
  'husband': 'Husband',
  'wife': 'Wife',
  'brother': 'Brother',
  'sister': 'Sister',
  'grandfather': 'Grandfather',
  'grandmother': 'Grandmother',
  'grandson': 'Grandson',
  'granddaughter': 'Granddaughter',
  'uncle': 'Uncle',
  'aunt': 'Aunt',
  'nephew': 'Nephew',
  'niece': 'Niece',
  
  // 用户搜索页面的翻译键
  'search_user': 'Search User',
  'enter_phone_or_email': 'Enter phone or email',
  'search_results': 'Search Results',
  'search_failed': 'Search failed',
};
