const Map<String, String> en = {
  'login': 'Login',
  'username': 'Username',
  'password': 'Password',
  'home': 'Home',
  'current_location': 'Current Location',
  'find_location': 'Find Location',
  'history_location': 'Location History',
  'track_location': 'Track Location',
  'tv_player': 'TV Player',
  'settings': 'Settings',
  'language_settings': 'Language Settings',
  'theme_color': 'Theme Mode',
  'current_language': 'Current Language',
  'current_theme': 'Current Theme',
  'family': 'My Family',
  'iptv': 'IPTV',
  'profile': 'Profile',
  'message': 'Message',
  'logout': 'Logout',
  'message_center': 'Message Center',
  'sender': 'Sender',
  'loading_more': 'Loading more...',
  'load_more': 'Load more', // 添加这个翻译键
  'fetch_message_failed': 'Failed to fetch messages',
  'user_login': 'User Login',
  'account': 'Account',
  'captcha': 'Captcha',
  'enter_account': 'Please enter account',
  'enter_password': 'Please enter password',
  'enter_captcha': 'Please enter captcha',
  'account_locked': 'Account locked, please try again in 10 minutes',
  'register_prompt': 'Don\'t have an account? Register now',
  'login_failed': 'Login failed',
  'unknown_error': 'Unknown error',
  'family_title': 'Family Tree',
  'loading_family_data': 'Loading family data...',
  'no_data': 'No data available',
  'unknown_member': 'Unknown Member',
  'unknown_relationship': 'Unknown Relationship',
  'delete_relationship': 'unbind user',
  'view_member_info': 'View information',
  'error': 'Error',
  'confirm': 'Confirm',
  'cancel': 'Cancel',
  // 添加TV列表页面的翻译键
  'tv_list': 'TV List',
  'loading_tv_channels': 'Loading TV channels...',
  'search_channels': 'Search channels',
  'no_tv_channels_found': 'No TV channels found',
  'unknown_channel': 'Unknown channel',
  'signal_sources': 'signal sources',
  'page': 'Page',
  'current_page': 'Current Page',
  'total': 'Total',
  'channels': 'channels',
  'previous_page': 'Previous Page',
  'next_page': 'Next Page',

  // 添加发送消息功能的翻译键
  'send_message': 'Send Message',
  'message_sent_successfully': 'Message sent successfully',
  'message_sent_failed': 'Message sent failed',
  'receiver_id': 'Receiver ID',
  'enter_receiver_id': 'Please enter receiver ID',
  'message_content': 'Message Content',
  'enter_message_content': 'Please enter message content',
  'user_not_logged_in': 'User not logged in',
  'please_enter_all_fields': 'Please fill in all fields',

  // 添加家族编辑页面的翻译键
  'add_family_relationships': 'Add Relationships',
  'selected_user': 'Selected User',
  'select_user': 'Select User',
  'select_relationship': 'Select Relationship',
  'relationship_required': 'Relationship is required',
  'save_relationships': 'Save Relationships',
  'please_add_at_least_one_relationship':
      'Please add at least one relationship',
  'success': 'Success',
  'relationships_saved': 'Relationships saved successfully',

  // 关系类型翻译
  'father': 'Father',
  'mother': 'Mother',
  'son': 'Son',
  'daughter': 'Daughter',
  'husband': 'Husband',
  'wife': 'Wife',
  'brother': 'Brother',
  'sister': 'Sister',
  'grandfather': 'Grandfather',
  'grandmother': 'Grandmother',
  'grandson': 'Grandson',
  'granddaughter': 'Granddaughter',
  'uncle': 'Uncle',
  'aunt': 'Aunt',
  'nephew': 'Nephew',
  'niece': 'Niece',

  // 用户搜索页面的翻译键
  'search_user': 'Search User',
  'enter_phone_or_email': 'Enter phone or email',
  'search_results': 'Search Results',
  'search_failed': 'Search failed',

  // Profile Page translations
  'select_image_source': 'Select Image Source',
  'select_from_gallery': 'Select from Gallery',
  'take_photo': 'Take Photo',
  'save_changes': 'Save Changes',
  'edit_profile': 'Edit Profile',
  'name': 'Name',
  'gender': 'Gender',
  'male': 'Male',
  'female': 'Female',
  'birth_date': 'Birth Date',
  'select_birth_date': 'Select Birth Date',
  'update_success': 'Update Success',
  'user_info_updated': 'User information updated successfully',
  'update_failed': 'Update Failed',
  'network_exception': 'Network exception, please try again later',
  'failed_to_fetch_user_info': 'Failed to fetch user information',
  'avatar_updated': 'Avatar updated successfully',
  'avatar_update_failed': 'Failed to update avatar',
  'avatar_upload_failed': 'Failed to upload avatar',
  // 在文件末尾添加以下内容
  // 补全Settings Page缺失的翻译键
  'check_new_version': 'Check if a new version is available',
  'confirm_clear_cache':
      'Are you sure you want to clear all cache data? This operation cannot be undone.',
  'cache_cleared': 'Cache cleared',
  'confirm_exit': 'Confirm Exit',
  'confirm_exit_app': 'Are you sure you want to exit the app?',
  'confirm_logout': 'Confirm Logout',
  'confirm_logout_msg': 'Are you sure you want to logout?',
  'found_new_version': 'Found new version ',
  'release_date': 'Release Date: ',
  'update_content': 'Update Content:',
  'force_update': '* This version must be updated',
  'no_update_needed': 'Current version is up to date',
  'current_env': 'Current Environment',
  'update': 'Update',
  'prod_env': 'Production Environment',
  'dev_env': 'Development Environment',
  'mock_env': 'Mock Environment',
  'unknown_environment': 'Unknown Environment',
  'default': 'Default',
  'light': 'Light',
  'dark': 'Dark',
  'english': 'English',
  'chinese': 'Chinese',
  'clear_login_info_and_return_to_login_page':
      'Clear login information and return to login page',
  'prompt': 'Prompt',
  'env_settings': 'Environment Settings',
  'check_updates': 'Check Updates',
  'clear_cache': 'Clear Cache',
  'clear_cache_confirm': 'Confirm clear cache?',
  'clear_cache_success': 'Cache cleared successfully',
  'clear_cache_failed': 'Failed to clear cache',
  'clear_all_data': 'Clear All Data',
  'exit_app': 'Exit App',
  'exit_application': 'Exit the app',
  'prod': 'Production',
  'dev': 'Development',
  'mock': 'Mock',
  // App Version Page translations
  'app_version': 'App Version',
  'refresh': 'Refresh',
  'version': 'Version',
  'no_version_info': 'No version information available',
  'error_fetching_versions': 'Error fetching version list',
  'retry_later': 'Please try again later',
  'fetch_version_failed': 'Failed to fetch version list',
  // Update Page translations
  'update_to_version': 'Update to version',
  'method_browser_download': 'Method 1: Browser Download',
  'download_via_browser': 'Download APK file via browser',
  'processing': 'Processing...',
  'browser_download': 'Browser Download',
  'method_app_download': 'Method 2: In-App Download',
  'download_and_install_in_app': 'Download and install APK directly in the app',
  'download_progress': 'Download progress:',
  'downloading': 'Downloading...',
  'in_app_download': 'In-App Download',
  'install_permission': 'Install Permission',
  'install_permission_required': 'Need to authorize "Install unknown apps" permission to install APK. Go to system settings to authorize?',
  'go_to_authorize': 'Go to Authorize',
  'browser_opened': 'Browser opened, starting download',
  'failed_to_open_browser': 'Failed to open browser',
  'apk_download_started': 'Starting APK download...',
  'apk_download_completed': 'APK download completed, installing...',
  'apk_install_started': 'APK installation started',
  'install_manually': 'Cannot install APK automatically, please install manually: ',
  // Live All Page translations
  'channel_list': 'Channel List',
  'view_by_group': 'View channels by group',
  'favorites': 'Favorites',
  'all': 'All',
  'no_favorite_channels': 'No favorite channels',
  'no_channel_data': 'No channel data',
  'unknown_tab': 'Unknown tab',
  'load_failed': 'Load failed:',
  'retry': 'Retry',
  'group': 'Group:',
  'language': 'Language:',
  'country': 'Country:',
  'play_channel': 'Play channel',
  'remove_favorite': 'Remove favorite',
  'add_favorite': 'Add favorite',
  'operation_failed': 'Operation failed, please try again',
  'operation_failed_with_error': 'Operation failed:',
  'channel_id_not_exist': 'Channel ID does not exist, cannot add to favorites',
  'removed_from_favorites': 'Removed from favorites',
  'added_to_favorites': 'Added to favorites',
  'channel_no_playable_link': 'This channel has no available playable link',
  // Live Group Page translations
  'channel_groups': 'Channel Groups',
  'no_channel_groups': 'No channel groups available',
  'search_channel_groups': 'Search channel groups',
  'group_channels': 'Group Channels',
  'view_channels_in_group': 'View channels in this group',
  
  // File Upload Page translations
  'file_upload': 'File Upload',
  'select_file': 'Select File',
  'select_file_to_upload': 'Select a file to upload',
  'supports_images_documents': 'Supports images, documents and other file types',
  'selected_file_info': 'Selected File Info',
  'file_name': 'File Name',
  'file_size': 'File Size',
  'file_path': 'File Path',
  'clear_selection': 'Clear Selection',
  'upload_file': 'Upload File',
  'upload_progress': 'Upload Progress',
  'file_upload_success': 'File uploaded successfully!',
  'file_upload_failed': 'File upload failed',
  'please_select_file_first': 'Please select a file first',
  'uploading': 'Uploading...',
  
  // File List Page translations
  'file_list': 'File List',
  'loading_files': 'Loading files...',
  'no_files': 'No files available',
  'upload_time': 'Upload Time',
  'download_file': 'Download File',
  'download_success': 'File downloaded successfully',
  'download_failed': 'File download failed',
  'save_path': 'Save path'
};
