package com.bage.dao;

import com.bage.domain.OauthClientDetails;

public interface OauthClientDetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbg.generated Wed May 01 13:20:23 CST 2019
     */
    int deleteByPrimaryKey(String clientId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbg.generated Wed May 01 13:20:23 CST 2019
     */
    int insert(OauthClientDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbg.generated Wed May 01 13:20:23 CST 2019
     */
    int insertSelective(OauthClientDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbg.generated Wed May 01 13:20:23 CST 2019
     */
    OauthClientDetails selectByPrimaryKey(String clientId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbg.generated Wed May 01 13:20:23 CST 2019
     */
    int updateByPrimaryKeySelective(OauthClientDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbg.generated Wed May 01 13:20:23 CST 2019
     */
    int updateByPrimaryKey(OauthClientDetails record);
}